### ISSUE TITLE
Improve staircase implementations, and some other bits in data.py

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1040]
This issue is merely here to serve me as a to-do list.

- [ ] QUEST creates grid of counter-intuitive dimensions #1005 
- [ ] Staircases should allow pre-defined intensity lists #1009
- [ ] `nTrials` parameter in `MultiStairHandler` is ambiguous #1016
- [x] PsiHandler API potentially counter-intuitive #1043
- [ ] Add tests for Psi method #1035
- [ ] `MultiStairHandler` does not support Psi method #1017
- [ ] Add Kesten staircase #1048
- [ ] Make staircase unit tests more PEP8-compliant (???)
- [ ] Subclass all staircases from common base class #1008
- [ ] Some methods in `data.py` violate LSP #1042
- [ ] StairHandler should support (nTrials OR nReversals) as termination criterion #1046
- [ ] StairHandler should support different step sizes for up and down steps #1047
- [ ] Allow specification of decimal separators when saving text data files #1049
- [x] QUEST intensity scaling should be removed #1006
- [x] Improve test coverage for staircase procedures #1007
- [x] Psi staircase not working? #1013
- [x] Staircases in `MultiStairHandler` execute, but never 'finish' #1015

**Comment by peircej** [comment]
Ha! I didn't know that we could insert check boxes in comments! :-)

**Comment by hoechenberger** [comment]
Pretty neat, eh? :) Just for the record, the syntax is:
```
- [ ] Unchecked item
- [x] Checked item
```
- [ ] Unchecked item
- [x] Checked item

**Comment by hoechenberger** [comment]
These issues were added to [a milestone](https://github.com/psychopy/psychopy/milestones/Refactor%20Staircases). Closing.
