### ISSUE TITLE
style-related refactoring

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1056]
To reduce technical debt and set the stage for further awesomeness, here's a summary of suggestions after discussion on the dev list. Ideally do them all at once, but that is not so realistic. Need to watch out for merge conflicts. I'll edit and check things off as we go.

Strong consensus, easy to do:
- [x] Revise imports: 
  - Remove all implicit relative imports. Use explicit relative for anything that is conceptually "local", and absolute for anything in (or going through) top-level (psychopy/).
  - Remove all use of wildcard imports, except in `contrib/`, plus some appropriate uses.
  - Remove all unused cruft imports (but not where deliberate). This can be tricky to tell in some cases, so I also added `# pylint: disable` directives on lines where unused imports should remain
- [x] Have a standard heading in each file:
  - `#!/usr/bin/env python2`, changing to `python` when support 2 and 3, or `python3` if/when only support python3
  -  `# -*- coding: utf-8 -*-` in all files, even those that do not need it
  - copyright line(s)
  - docstring
  - `from __future__ import (absolute_imports, print_function, division, unicode_literals)` to all files (but not demos). Handle `division` and `unicode_literals` (see #1061) separately, but might be easy.
- [x] Several smaller things that can be done at once 
  - Update all old-style classes to new style. Find them with `git grep -ne ':$' | grep ':class*' | grep \(\)`. Classes should typically call `super().__init__()`, even when inheriting directly from `object`, unless there's a reason not to.
  - Remove all mutables as default parameter values
  - Replace exec with eval whenever possible, which is most but not all places.
  - Remove all bare except statements. Use `except Exception:` instead when need very general. It allows `sys.exit()` and `KeyboardInterrupt` to raise (= good). Use a more precise Exception when possible, of course
- [x] Remove code that exclusively supports python 2.6.x or earlier (like the `_relpath()` function in builder.py). Need to update documentation to say works with python 2.7 only.
- [x] Fewer long lines; getting to none is not worth it, and not compromising readability is important. PEP-8 suggests 79 chars. Using `autopep8` will do a lot of this, but review by human is important too (otherwise things can look bad). 
- [ ] Add more doc-strings to files, classes, methods, functions
- [ ] Not discussed but seems uncontroversial: 
  - Rename variables that are reserved words in python, including `id`, `file`, `property`, and others. See pylint `redefined-builtin` warnings.

Strong consensus, just need the usual care to avoid merge conflicts and be backwards compatible:
- [x] Split builder.py into several files (#1074)
- [x] Split data.py (#1053)
- [x] Split sound.py, move microphone and voicekey inside sound/

iohub:
- [ ] autopep8 + manual review: `iohub/`
- [x] Revise imports (ala #1063)

Good consensus, need to wide coordination to avoid merge conflagrations:
- [x] Do autopep8 on everything. Review by hand.
- [ ] autopep8 + review: `iohub/`, `tests/`, top level `psychopy/` (set-up stuff)
- [x] Ensure a final newline in every file when autopep8
- [x] Remove all trailing whitespace when autopep8
- [ ] Standardize the doc-string style (numpy vs google)

Strong consensus, unclear timeline:
- [x] Support python3 (#1061).

No consensus, and still needs more community input:
- [x] Move implementations out of `__init__.py` files, use those files only for imports (#1054)

Decided against:
- [x] Do not migrate `lowerCamelCase` -> `lower_camel_case` for vars and methods / functions.
- [x] Not worth it to rename files for consistency with existing lowerCamel (MonitorCenter.py to be monitorCenter.py, Darwin.spec -> darwin.spec, other .spec files; app/Resources/ (directory) -> app/resources)

**Comment by hoechenberger** [comment]
One point that wasn't brought up on the mailing list is:
Move implementations out of __init__.py in ioHub (#1054)

But I'm still waiting for input on this one :)

**Comment by peircej** [comment]
For docs I'm pretty comfortable with things being made consistent as long as sphinx doesn't start spitting more errors. I've just pushed a commit here that fixes several issues 
In terms of the decision about which format to use I found that numpy doc strings give sphinx autodoc a lot of issues and it those can't be turned off in sphinx config then these will annoy me a great deal.

Sphinx is very picky so any docs work should be done v carefully

**Comment by hoechenberger** [comment]
Hm, I've always used numpydoc style with sphinx autodoc for my own projects and never experienced any problems. Will definitely look into this, and of course I won't start any transition if that somehow breaks autogeneration (or makes makes it more annoying) .

**Comment by jeremygray** [comment]
@hoechenberger you can always just do `make html` inside `psychopy/docs/` to see what happens. But if you have other packages to help preprocess the humpy docstrings (like: Napoleon https://pypi.python.org/pypi/sphinxcontrib-napoleon) then that needs to be worked out as well.

**Comment by hoechenberger** [comment]
@jeremygray  Yes, of course. I was thinking about using napoleon :)

**Comment by toddrjen** [comment]
@jeremygray 

> remove implicit relative imports

Probably should do `from __future__ import absolute_import` to make sure this doesn't accidentally get re-added.

> add from __future__ import print_function to files that have a print statement

I would put `from __future__ import absolute_import, print_function` at the top of every file, period, just as a habit.  `print` may be added at any time later, so I think it is better to get everything consistent up-front.  Looking at projects like numpy and matplotlib, this is also what they appear to do (actually they do `from __future__ import absolute_import, division, print_function`), but `division` is a more substantial change that will likely come later).

> fewer long lines (getting to none is not worth it); the latest pylint default is 100 chars

pep8 says 79, I think it would be good to keep to that wherever possible.  Of course not where it hurts readability too much.

> remove all unused imports as appropriate (but not where deliberate, like misc.py). 

I would also try to add more conditional imports where possible, to make it possible to run psychopy with as few dependencies as possible.

> support python3

I think it would be worthwhile making a separate issue for this, or at least split it here into multiple steps.

**Comment by hoechenberger** [comment]
> I would put from __future__ import absolute_import, print_function at the top of every file, period, just as a habit.

I also agree with this. As it was mentioned, we should be careful with the additional `from __future__ import division`, but I mean, we could try it out and see if anything breaks, no? :)

> pep8 says 79, I think it would be good to keep to that wherever possible. Of course not where it hurts readability too much.

I would also very strongly suggest to not go above 80 chars/line, as it seriously impairs readability, even if one does not have to scroll (yet). Breaking this limit should be a very rare exception, and be strongly discouraged except there is a very good reason not to adhere to the limit in a particular situation.

As a general not, I suggest that as soon as we have agreed upon the measures to be taken, we create separate issues for each of them, and collect them in a milestone.

**Comment by derNarr** [comment]
What is the reason for:

* Remove -*- coding: utf-8 -*- from files that do not need it (most do not)

As code would break, if someone inserts non ascii chracters but forgets to put the line back in, am I wrong?

**Comment by hoechenberger** [comment]
I would also say that we should ADD this to any files missing it, i.e., create some kind of header common to all source files, as was proposed with regard to the import statements.

**Comment by jeremygray** [comment]
>
> I would also say that we should ADD this to any files missing it, i.e.,
> create some kind of header common to all source files, as was proposed with
> regard to the import statements.


I actually thought this too (and recently added it to all of the Coder
demos). Then I saw the following in PEP-8. Maybe I mis-interpreted
it? "Files using ASCII (in Python 2) or UTF-8 (in Python 3) should not have
an encoding declaration."

 (http://legacy.python.org/dev/peps/pep-0008/#source-file-encoding)

**Comment by hoechenberger** [comment]
@jeremygray Yes this is true, but as long as we are trying to support both platforms (Python 2 and 3) simultaneously, I think we should be explicit... No? I mean, the move to Python 3 is another step, is it not? :)

**Comment by derNarr** [comment]
With Python3 in mind I would strongly suggest to keep the -*- coding: utf-8 -*- line as well as the inheritance of (object) in class definitions ("new style classes"). Both becomes obsolete in Python3, but mimics Python3 behaviour in Python2.

**Comment by derNarr** [comment]
We should also put `from __future__ import unicode_literals` into **every** file (not only in those who needs it). But this might break stuff, in my experience even more likely than `division`.

**Comment by hoechenberger** [comment]
I've got the feeling we are scattering discussions all over different places (this issue, mailing list, #1061). We should try to consolidate :)

**Comment by jeremygray** [comment]
I am persuaded about including a coding declaration in every file.
Conceptually it makes sense to do so for unicode_literals as well but I
have never looked into that and do not have a feel for how disruptive it
might be.

Moving all classes to inherit from object is a definite yes, already in the
plan

--Jeremy

**Comment by jeremygray** [comment]
This issue #1056 is intended as a consolidation of "mere style" issues. I'm editing the top post in this thread to reflect ideas and the consensus expressed throughout. Let me know if I miss anything. #1061 is intended as similar, but only for python 3 issues; there will be some overlap.

**Comment by hoechenberger** [comment]
Thanks, Jeremy!

**Comment by jeremygray** [comment]
@qbilius Are any of the style issues raised here of concern for psychopy_ext?

**Comment by qbilius** [comment]
Looks great, I should probably put some effort to update psychopy_ext accordingly. Definitely Python 3 is in the pipeline.

**Comment by peircej** [comment]
Most of this is either completed or obsolete
