### ISSUE TITLE
Builder UX issues

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2132]
I've only recently started using the Builder again after taking a break of several years. I always found it difficult to force my ideas into the "Builder type of thinking", and my paradigms would have required to add quite some Code Components anyway, so I decided to write all code from scratch right from the beginning.

We now have some students in our lab that are still learning the basics of Python and I thought maybe I/we could give Builder another try to make it easier for them to implement their own experiments.

I came across a number of small things that I thought could be improved to help make for a better UX, which I will list in the following.

- [ ] `Insert Routine` and `Insert Loop` buttons are stuck to the left of the Flow panel. This makes it cumbersome to add additional Routines or Loops at the end of an experiment already consisting of numerous Routines, as one would first have to scroll all the way back to the left to reach the buttons, click them, then scroll back all the way to the right to insert the element.
![inserting routine](https://user-images.githubusercontent.com/2046265/49687795-97ce7400-fb08-11e8-9622-57ee28bfe7f2.gif)
(One can also see here that the scrolling position is not updated properly after the Routine has been inserted)

  **Possible Solution**: The Flow panel should consist of two sub-panels, one that contains the buttons, and one containing the Routines and Loops and a horizontal scroll bar. That way, the buttons would always remain on-screen, even when scrolling to the far-right Routines in a large experiment.
- [x] Inserting longer portions of text without line-breaks into the Text Component (and checking what's written there) is annoying as one would have to scroll around the window, since it does not support soft-wraps.
![text component](https://user-images.githubusercontent.com/2046265/49687887-563ec880-fb0a-11e8-89af-c0d4ae048a70.gif)

  **Possible Solution**: Remove the horizontal scroll bar from the input field, and add support for soft-wraps.
- [ ] The way one moves a Component inside a Routine (moving it up / down) is very atypical in the sense that I've never seen anything like that in any other app I've used for the past 3 years or so: one has to right-click and then click on "move up" or "move down", respectively. With a modern app I would expect to find some kind of clickable "anchor" left of each Component which I can simply click into and then drag it to the desired position.

  **Possible Solution**:  Insert a drag-and-droppable icon / anchor left of each Component present in a Routine, allowing the user to reorder Components via drag and drop.
- [x] The identity of `STOPPED` and `FINISHED` is confusing. In `psychopy.constants` we define:
  ```python
  STOPPED = -1
  FINISHED = STOPPED
  ```
  Now, the `ParallelOutComponent` produces code such as the following:
  ```python
    if p_port.status == STARTED and frameN >= (p_port.frameNStart + 10):
        p_port.status = STOPPED
        p_port.setData(int(0))
    
    # check if all components have finished
    if not continueRoutine:  # a component has requested a forced-end of Routine
        break
    continueRoutine = False  # will revert to True if at least one component still running
    for thisComponent in trialComponents:
        if hasattr(thisComponent, "status") and thisComponent.status != FINISHED:
            continueRoutine = True
            break  # at least one component has not yet finished
  ```
  It actually took me several minutes (and an excursion to said `psychopy.constants` module) to discover why the Routine would even finish. The issue here is that we check for all components whether their status is `!= FINISHED`, while `p_port.status` is being set to `STOPPED`. Extremely confusing.

  **Possible Solution**: Ensure that **all** Components set their status to _either_ `STOPPED`_or_ `FINISHED`, and adjust the `check if all components have finished` code such that it only refers to the agreed-upon name of the status. Since `STOPPED` and `FINISHED` are identical, this would even preserve backward compatibility, while legibility of the generated code would be improved.

- [x] When renaming a Routine, the user is presented with an empty input field. This is unexpected in modern UIs and the input field should actually contain the current name of the Routine to be renamed.

  **Possible Solution**:  The input field should contain the current Routine name, which can then be easily edited. _Implemented in #2159._

- [x] At least on macOS, the app would always ask twice before overwriting a file, as described in #2113.

- [x] The order of the Routine tabs does not match the order of the Routines in the experiment; instead, they are sorted alphabetically. I find this very conter-intuitive, also considering that this re-ordering only occurs after you've saved and reopened the file.

  **Possible Solution**: The Routine tab order should match the order of Routines in the experiment. See also #1020.

- [x] #4241
- [x] Flickering of the flow panel when moving around the dot representing where routine/loop (@mmagnuski)
- [x] Changes to Builder readme files are lost when window is closed without prior explicit saving. (#2161)
- [x] Opening a file in Builder doesn't clear the Routine tabs of previously loaded file(s) (#2336)

**Comment by hoechenberger** [comment]
Maybe the tab close buttons should be removed altogether. Might as well remove the possibility to move/reorder tabs while at it :) and just order according to Routine succession in the Flow.

**Comment by mmagnuski** [comment]
@hoechenberger That is the easiest solution. But having a subset of routines open as tabs might be useful when working on big experiments with many routines.

**Comment by m-macaskill** [comment]
Agree that the flow panel insertion controls should ideally be static rather than move as the flow panel scrolls.

Some of the other points might be misunderstanding the intended conceptual model of the Builder interface, which separates the routine definitions and the flow. The tabs *are* the routines, so deleting one *must necessarily* result in any associated entries in the flow being deleted. If a routine name occurred in the flow but its definition didn't exist, we would consider it to be a corrupted .psyexp file. Conversely, removing a routine from the flow does nothing to the routine itself. The routine definitions exist independently of whether they have an entry (or multiple entries) in the flow panel.

I think the problem here is the UI for deleting a routine. One doesn't normally think of closing a tab as resulting in the _destruction_ of data: normally it is just closing a view of that data. I don't know if its possible to replace the "close" widget with something more clearly representing the destructive nature of clicking it, like a small trash can or something? Or as Richard suggests, perhaps better to remove the close widget altogether, and put an explicit "Delete routine" button inside the tab?

Lastly, I think the order of tabs should be available to the user to control. Again, I don't think that the order in the flow is relevant here. The user might want convenient access to their most-edited routines at the left, rather than some uninteresting instruction routines, for example. But currently on a Mac, when I try to change the order of tabs, instead, they do this weird dance and get separated vertically (so they no longer take up the full pane available), rather than shuffle order horizontally. So that could certainly be improved...

**Comment by mmagnuski** [comment]
> One doesn't normally think of closing a tab as resulting in the destruction of data

That's exactly what I meant - I think routine deletion by tab closing is highly counterituitive. Tabs usually represent views so closing a tab removes a view onto something but not the thing itself. From this point of view removing the close widget and adding delete routine button would be the best option.
However - closing a view of a routine without deleting it would still be very useful. But I understand that it would require too much overhaul so tab reordering is a good hack for that. BTW I didn't notice that tabs could be reordered (on Windows at least) becasue I almost always bring routines into view by clinging on the flow panel, so I very rarely click on the tabs. :)

**Comment by peircej** [comment]
Wow there are lots of different things in this issue! Te short story is that, for nearly all of them, I'm happy to take pull requests.

1. buttons in Flow. I agree it would be great if they were always visible. Happy to take a PR
2. soft-wrap Text contents. You can now make the dialog really big and the text box grows (that didn't used to work). I _think_ I'm on board with soft-wrap as well, except that users might expect the wrap on the screen to occur in the same places? Maybe not. I don't mind.
3. drag components to change order. Agreed. Right-click was the poor-man's drag and I would love them to be draggable instead. Would _love_ to see a PR on that!
4. FINISHED and STOPPED. Yes, sadly somewhere along the line these two names got added for essentially the same thing and it would be great to choose one and be consistent (but both need importing in Builder Experiments to maintain compatibility). Happy to take a PR
5. Better default when renaming a Routine. Yes. Happy to take a PR
6. Double-question on overwrite. Yes. Happy to take a PR
7. Routine order. I disagree with "The same order as in the Experiment (Flow?)". Some Routines might not be on the Flow. Some might be there twice. Ideally the Routines would keep whatever order they were put into by the user. They initially have the order the get created in. They can be dragged to a custom order but, either way, we don't currently check that order during save. In fact, the reason the get stored alphabetically is so that the stored experiment file has a predictable order. We could get rid of that "feature" if we're careful always to check the order of the tabs and reload them in that order. Basically, I'm happy to see change here, but not change to the order of the Flow.
8. closing tab means delete Routine. It does and I don't see an alternative at the moment. This is the only way to delete a Routine, and we need some way. Possibly the icon can be changed to a dustbin to make the function more clear? 
9. Flickering Flow during insert. Happy to take a PR

**Comment by peircej** [comment]
I'm happy with FINISHED

**Comment by hoechenberger** [comment]
> * closing tab means delete Routine. It does and I don't see an alternative at the moment. This is the only way to delete a Routine, and we need some way. Possibly the icon can be changed to a dustbin to make the function more clear?

I like the idea of displaying a small dustbin if that's feasible! We should _definitely_ add to a confirmation dialog in any case! Currently closing the tab destroys the Routine without asking for any kind of confirmation.

**Comment by hoechenberger** [comment]
Another issue: I can copy, but not paste Routines.

![screen recording 2018-12-20 at 20 10 25](https://user-images.githubusercontent.com/2046265/50305620-ab2bf880-0493-11e9-943c-3c4493aa9f9d.gif)

**Comment by hoechenberger** [comment]
Yet another one: something is off with the color indicator of the Routines, showing whether a Routine has a fixed / expected duration or not. Behavior is inconsistent:

![screen recording 2018-12-20 at 20 15 15](https://user-images.githubusercontent.com/2046265/50305841-5d63c000-0494-11e9-9d93-b48c997c550c.gif)

**Comment by mmagnuski** [comment]
@hoechenberger 
You paste routines from the `Experiment` menu. That is counterintuitive, I know, I learnt that only this year, although I'd say it's much less counterintuitive than `close tab -> delete routine`. :)
The routine color on the other hand is updated only from time to time (don't know exactly when), but always when something is changed in the experiment flow.

**Comment by hoechenberger** [comment]
One more:

The "Open Recent" menu is not properly saved when only the experiment window (and not the entire app) is closed). Witnessed this behavior on both Windows 10 and macOS.

![untitled](https://user-images.githubusercontent.com/2046265/50307262-37401f00-0498-11e9-8e46-4268a6f9a701.gif)

**Comment by hoechenberger** [comment]
> You paste routines from the `Experiment` menu. That is counterintuitive, I know, I learnt that only this year, although I'd say it's much less counterintuitive than `close tab -> delete routine`. :)

WOW! I would have _never_ figured!

> The routine color on the other hand is updated only from time to time (don't know exactly when), but always when something is changed in the experiment flow.

If I insert a single Component, then Undo and Redo, the Routine suddenly turns green. I would assume there is a bug somewhere.

**Comment by hoechenberger** [comment]
Last one for today:

(I think we already discussed that somewhere, but couldn't it anymore) – The "Experiment Settings" button looks like a "Switch to fullscreen mode" button. Literally no-one I've ever introduced to PsychoPy has ever intuitively discovered that button. We should replace the icon with something more clear. How about, like, a gear? Gear – Clear! Would even rhyme! :D

**Comment by hoechenberger** [comment]
Oh by the way, I still like you all and PsychoPy. It's just certain things that _drive me insane!!!_

**Comment by m-macaskill** [comment]
I ***do*** very much like the idea of new toolbar icons for both the Preferences and Experiment Settings. Currently, the Preferences icon looks like "tools", and the experiment settings icon has always been inscrutable to me. I like the idea of a big gear icon for Preferences, and a visually and semantically-related one for experiment settings (e.g. a big gear paired with a smaller one).

**Comment by peircej** [comment]
Changing the icons is trivial. Feel free to go and find better ones and insert them into the app resources.

The issue with the color of Routines on the Flow is probably just a matter of not updating the view at the right time (i.e. a change was made to the Routines but the Flow wasn't refreshed)

The issue with recent files could be fixed by doing prefs.save() more often (e.g. when the view closes or as soon as the files is loaded).

But folks this isn't a useful way for me/us to track/fix issues. I'm never going to come back to a long rambling thread like this to find the next job to work on, so this thread is effectively useless except for you to release steam. Basically, if these things matter to you a lot then fix them. If they matter to you just a little then create an individual issue that describes just that issue (the clue was in the name! 😉 ) and hope that someone else fixes it one day!

**Comment by mmagnuski** [comment]
@peircej 
I think we could at least make a nice checklist out of all these rambling trajectories, grouping them in some meaningful way in the top post. I don't think it's such a bad idea to gather issues first in a more brainstorming fashion and then organize. I would be happy to submit PRs to fix some of these issues but I still don't know psychopy internals well enough to be of help and not a burden as a PR.
Although some of the posts here may sound as if we were venting frsutration this is not the case - we love psychopy and want it to get even better - and grouping some of the UI problems that we and our students have encountered seemed like something easy we could do to help.

**Comment by mmagnuski** [comment]
We can open the issues for individual checkboxes here and link them here as a gathering place for UI-related stuff. Would that be ok for you @peircej?

**Comment by peircej** [comment]
Yes. Sorry, I didn't mean to sound grumpy. If this works for you to organise what needs doing that's fine, of course

**Comment by peircej** [comment]
For exp settings icon there are a couple of cog icons in the CrystalClear icon set, where most of our icons originate. There's a simple cog but then I feel like it's ambiguous whether it's application settings or experiment settings. The following 2 options have a cog but also some sense of a window that hopefully gives a sense of "experiment":
![image](https://user-images.githubusercontent.com/380582/50589730-abf36000-0e7f-11e9-803e-f1f21c552d5b.png)
or this:
![image](https://user-images.githubusercontent.com/380582/50590097-659f0080-0e81-11e9-9bf7-a5ecb35dbcb4.png)

I have a slight preference for the second one.

Also, shall I get rid of the application preference altogether? That was fine in the toolbar when there were only 6 or 7 buttons but now there's more I think that should go (not many apps have settings in the toolbar, only the menus)

**Comment by hoechenberger** [comment]
Cool!! I think the first icon looks better, but the second one is clearer in depicting its purpose! So I’d favor the second one. 

Regarding the app prefs: yes, I like your idea of removing them from the toolbar.

Cheers!

--
